spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://keycloak:8080/realms/library-realm
#            issuer-uri: http://localhost:8080/realms/library-realm
#            issuer-uri: "{baseUrl}:8080/realms/library-realm"
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak-provider
            scope: openid
            client-id: gateway-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  redirectService: library-service